### ISSUE TITLE
combine avatar & sounds panel into one media panel

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#109]
avatars & sounds can be displayed together in a media panel, similar to what we currently have in UpStage v3. the default display should be a sortable table, sortable by name, type, uploader, date, stage, tags ...

**Comment by rohrlach** [comment]
Okay - should this then supersede #107 ?

**Comment by vickis** [comment]
agreed - to the sort by & your suggestion Paul

**Comment by helenvarley** [comment]
both of these issues are closed but the default display is still icons rather than list ... ??

**Comment by rohrlach** [comment]
Ahh D'oh! Forgot to push that commit... It's done, just not deployed yet

**Comment by vickis** [comment]
seems to be the option to either have thumbnails or a list which works well :)On 8/05/2017, at 8:40 PM, Helen Varley Jamieson <notifications@github.com> wrote:both of these issues are closed but the default display is still icons rather than list ... ??—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/upstage-org/limelight","title":"upstage-org/limelight","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/upstage-org/limelight" class="">https://github.com/upstage-org/limelight</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@helenvarley in #109: both of these issues are closed but the default display is still icons rather than list ... ??"}],"action":{"name":"View Issue","url":"<a href="https://github.com/upstage-org/limelight/issues/109#issuecomment-299807714" class="">https://github.com/upstage-org/limelight/issues/109#issuecomment-299807714</a>"}}}

**Comment by helenvarley** [comment]
i still want the list view to be the default :)
imagine when there are 200 media items to display ... or more ...

**Comment by vickis** [comment]
Sure thats all good 
Die in the next commit eh?

**Comment by rohrlach** [comment]
Haha yes it is - Which I still forgot to push. My bad.

**Comment by rohrlach** [comment]
Will be deployed in about an hour

**Comment by helenvarley** [comment]
looking good - but i still want to have the list view as default :)

**Comment by vickis** [comment]
think you will have your wish but it didn’t go into the last commit right?
i have emailed stefan and the biz advisor today t plan for monday’s meeting …

**Comment by rohrlach** [comment]
Hahaha whoops... I'm​ starting to lose track as I keep swapping between two machines.

**Comment by rohrlach** [comment]
![screenshot from 2017-05-23 10-10-28](https://cloud.githubusercontent.com/assets/2830313/26358289/117ab60e-3fa0-11e7-9eed-53310a70d919.png)

**Comment by helenvarley** [comment]
do we not still need to adjust the green colour here so that you can actually read the media names on the green bars?

**Comment by rohrlach** [comment]
Yes. But it's covered in another ticket
