### ISSUE TITLE
Thoughts

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#122]
Relates to #72 

Utilizes the Chat Modifier Framework (#123)

For a player:
- [x] prefixing a chat message with a colon ':' constitutes a 'Thought'
- [x] Thoughts appear in the chat window as a light blue (0xadd8e6) thin font
- [x] Players may also utilize a checkbox to activate this modifier

**Comment by rohrlach** [comment]
Deploys in 10 mins

**Comment by vickis** [comment]
: Great :)

**Comment by helenvarley** [comment]
have tested shouting & thinking (in firefox on ubuntu) & both work, using the checkboxes or manually typing the command.
the multicoloured backgrounds for the chat text that have just appeared are ... vibrant!!! ;) can this please be an option, that one could set in the edit stage screen perhaps? i think that for many performances, it would be a bit too much, distracting from the onstage images. also the text is now separated out quite a lot more so that you see less in the chat window, which isn't ideal.

**Comment by helenvarley** [comment]
by the way, should we note here that for thinking (& shouting) there should also be a corresponding change in the way the avatar's speech bubble displays on stage?

**Comment by vickis** [comment]
yes that would be great!
used to be the bubbly shape for thinking and the spikes for shout - extra visual info to support the text change

maybe we could have yellow for cheerful (shortcut ^)
and purple for ethereal … (*)
dark orange for sinister … ($)

ha ha

**Comment by rohrlach** [comment]
I think it makes sense to put speech bubble issues in after we have controllable Avatars.

Will come back to the refinement here
