### ISSUE TITLE
Users can use their Nickname to Log in.

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#166]
currently it's only possible to log in with your email address. previously in UpStage it has always been username. is there a reason for using email address? if there's no reason, then i'd prefer username - simply because it's quicker ...

**Comment by rohrlach** [comment]
Erm... I think it's because I added nicknames after the fact.

**Comment by helenvarley** [comment]
ok; can it be possible to log in with either? (could be useful to log in with email if you've forgotten your username?)

**Comment by vickis** [comment]
Don't forget there is the forgot password link :)

**Comment by rohrlach** [comment]
Yes of course

**Comment by thongteav** [comment]
I would imagine that they're in the same text field. But I could be wrong.

**Comment by helenvarley** [comment]
username & nickname are the same

**Comment by rohrlach** [comment]
That's correct.

Unfortunately, we've created ambiguity where the term 'nickname' can refer to the nickname field for the ```User``` model and also the concept of renaming an avatar in the performance space.

I used the term "nickname" for users because it's not a defining characteristic (IE: can be changed at will) so linguistically, this made more sense to me.

In any case, @thongteav is correct - a user should see something like this:

![image](https://user-images.githubusercontent.com/2830313/38619392-0a4de2ca-3d6a-11e8-9143-4a5d59038ce0.png)
And should work as implied.

I may opt to rename the field on the user model, but I'll open a new issue for that.

**Comment by rohrlach** [comment]
Also note - being that this a security related change, I will be scrutinizing the solution carefully.

**Comment by helenvarley** [comment]
i would be inclined to go for "username" for something that refers to the player, since they are the user. 
to me "nickname" could relate to the avatar. especially as in UpStage we have always had the command "/nick" to change the name of the avatar ...

**Comment by rohrlach** [comment]
@helenvarley I have renamed the field as requested.  Please validate.

**Comment by helenvarley** [comment]
yep, looks good & works :)
