### ISSUE TITLE
Avatar Tab: rollover for thumbnails to show avatar name

### ISSUE THREAD

**Issue by helenvarley** [upstage-org/limelight#177]
When you roll the cursor over the thumbnail of an avatar in the on-stage Avatar palette, the name of the avatar should appear.

**Comment by helenvarley** [comment]
tested & working on linux, firefox & chrome :)
(is @vickis testing on mac?)

**Comment by rohrlach** [comment]
Works fine on Mac

**Comment by vickis** [comment]
Arohamai everyone
Not sure if you're aware but since tuesday vodafone/paradise clear have been experiencong major issues
Eg i just now 2130 friday got this email some seem to
Come in around the time they are sent others as this days late and in no particular order and sometimes several times ... 
So again apologies if there are major delays or double ups in anything you sent/ i am replying to 

Its a mare!
