### ISSUE TITLE
accessing the stage in firefox on a mac

### ISSUE THREAD

**Issue by vickis** [upstage-org/limelight#198]
When i am logged into Limelight on Firefox 48.0 on Mac El Capitain 10.11.3 I cannot actually enter a stage becuse clicking on the stage link always takes me to the stage edit screen ....

**Comment by helenvarley** [comment]
i just tried on my old mac, OS 10.6.8., using Firefox 48.0.2. in audience mode, the stage links on the welcome page take me to the stage. when i am logged in, the links also take me to the stage. (but i am not able to hold an avatar).

**Comment by rohrlach** [comment]
@vickis I'm assuming you don't have the browser window maximized - The window size (or rather, size and resolution) leads bootstrap to think you're using a tablet and disables the stage.

@helenvarley can you have a look at the browser console (F12) and see if it reports any errors?

**Comment by helenvarley** [comment]
we cannot expect everyone using a computer will have their browser window maximised. i normally don't, & especially not when i am using UpStage, since i'm often switching between other apps e.g. for streaming or a text. it has to work properly no matter how people have their browser window. 

i just tested now in firefox (linux) when the browser window is not maximised, & the link from the welcome page went to the stage edit screen. however using chrome on linux, not maximised, the link goes to the stage.

i think it's very confusing to have things work differently like this. if the problem is that we need it to function one way for mobiles & another way for computers, can't the software recognise the device & deliver accordingly??

**Comment by helenvarley** [comment]
@rohrlach - in answer to your question, the errors are: 
App.canvas is null
document.querySelectorAll(...).forEach is not a function
document.querySelectorAll(...).forEach is not a function

**Comment by rohrlach** [comment]
@helenvarley  thanks, I'll try to recreate that.

In regard to the screen sizes - Not really, Apps running in the browser have very little access to information about the machine the browser is running on (Security) The viewport (which relates to screen size, or rather, window size) really is the only indicator.

The other option is to drop the constraint - But that will lead to tablet/mobile users entering the stage and not really being able to use it.

I guess the call is yours - to get around the "windowed mode on a lower resolution laptop" issue I can allow the tablet screen size to enter the stage? This I think would be the best compromise.

**Comment by helenvarley** [comment]
yes that sounds good. we have to assume that many people will not have their browsers maximised, & it will be really confusing if the links sometimes take you where you expect them to & other times not.
if tablet/mobile users enter the stage, it will still work, won't it? they won't be able to easily enter text in the chat, but they will be able to see & hear what's going on, won't they? so we might as well let them in, even if the experience is limited. i think this is preferable to the current situation.

**Comment by rohrlach** [comment]
10 mins

**Comment by vickis** [comment]
Agree :)

**Comment by helenvarley** [comment]
now when my browser window is reduced, i can enter the stages from the links on the welcome page. :)

**Comment by rohrlach** [comment]
@vickis can you confirm and close

**Comment by vickis** [comment]
i am able to enter the stage on firefox (but not hold avatars...)
the browser resizes with the drawing intact... although the 'tools' get a bit messed about :)
