### ISSUE TITLE
Assigning Avatars and Sounds grid layout and order

### ISSUE THREAD

**Issue by charlie0605** [upstage-org/limelight#244]
when on a smaller window the list and the delete button divides into 2 rows and the list is not ordered for Avatars and Sounds
![image](https://user-images.githubusercontent.com/25602185/30406793-33543adc-9948-11e7-9f81-c23448469e82.png)

**Comment by rohrlach** [comment]
Hang on - wasn't this actually ADDRESSED in #241 ?

**Comment by charlie0605** [comment]
#241 is about backdrops, I though it would have to be a new issue if Avatars and Sounds are doing the same.

**Comment by rohrlach** [comment]
Okay. That's fine

**Comment by charlie0605** [comment]
![image](https://user-images.githubusercontent.com/25602185/30411694-aef1e22a-9966-11e7-8386-e51418dc3234.png)
![image](https://user-images.githubusercontent.com/25602185/30411702-bdf5bef4-9966-11e7-8964-3c57d6674bba.png)

**Comment by charlie0605** [comment]
@rohrlach I'm trying to sort the avatar on stage by its name, but the avatar_stages doesn't contain the name of the avatar. Do you have any suggestions on how I could sort it?

**Comment by rohrlach** [comment]
@charlie0605 assuming you're trying to sort an array of AvatarStage objects:

``` @avatar_stages.sort { |x| x.avatar.name }```

**Comment by rohrlach** [comment]
@helenvarley @vickis Please refer to the discussion in #248 for full context

**Comment by rohrlach** [comment]
Passing this issue based on the stated objective of the issue.  Note that some fixes explained by @charlie0605 in #248 are not actually addressed - Specifically, when attempting to assign an existing tag to a stage, server will return HTTP/422 (Unprocessable Entity) so we find ourselves in the situation where although this issue is complete, the PR isn't - This is why PRs should not deviate from their intended goal.
