### ISSUE TITLE
Change Cursor to Reflect Controls

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#322]
The cursor should change depending on the focused toolbox tab.  For example, when controlling an avatar - it should be a hand. A pencil when drawing etc.

**Comment by alexanderglenn** [comment]
Just to clarify; When the drawing tab is focused, then the cursor should change to a pencil when over the canvas?

**Comment by helenvarley** [comment]
nice idea! that would help you to remember which palette you're in :+1:

**Comment by alexanderglenn** [comment]
I have set custom icons when the drawing tab is selected and the user hovers the cursor over the canvas. The cursor changes to a pencil icon. The same happens when the avatar tabs is selected; the cursor changes to a hand icon.
Should the cursor change when the audio and backdrop tabs are selected?

**Comment by alexanderglenn** [comment]
Which icons and at what sizes do you want to be used? The pencil and hand icons I have currently are from http://www.iconarchive.com/show/pretty-office-10-icons-by-custom-icon-design/Pencil-icon.html
It looks like the icons are free to use.

**Comment by thongteav** [comment]
Or something more simple like:
![image](https://user-images.githubusercontent.com/26214298/38840070-d9711fa6-4231-11e8-969c-239b9dd79a7b.png)
[Pencil Icon](http://www.iconarchive.com/show/outline-icons-by-designcontest/Pencil-icon.html)

Although these icons are free, we still need to give credit to the artist. Do you know how it's usually been done? @rohrlach I usually work with just an image in a paragraph and put the credit below the image. But I'm not sure how it's done for a cursor.

**Comment by helenvarley** [comment]
hi team, please do NOT use any fancy icons for the cursor. it's a good idea to have a small change e.g. to a pencil as a reminder to the player that the action will be different. but something like http://www.iconarchive.com/show/pretty-office-10-icons-by-custom-icon-design/Pencil-icon.html is actually going to add distraction to the stage for the player, rather than be helpful.

when you are in the audio or backdrop palette, you should still be able to move your avatar on the stage, so the function of the cursor over the stage area does not change. therefore there is no need for a different icon. the only time it changes is with the drawing palette.

**Comment by vickis** [comment]
agree just a simple pencil for drawing would be helpful
but limiting distraction and potential for confusion is best for all users
especially new ones :)

**Comment by helenvarley** [comment]
great :)
