### ISSUE TITLE
Constrain Upload Formats

### ISSUE THREAD

**Issue by rohrlach** [upstage-org/limelight#95]
When uploading files, users should not be allowed to upload whatever they like.

Specifically:
- [ ] When adding an Avatar, users should only be able to upload images
- [ ] When adding a Sound, users should only be able to upload audio files

**Comment by helenvarley** [comment]
do we need to specify filetypes at this stage? e,g, can we upload audio files other than mp3s? 

it would be great to have as wide a range of filetypes as possible, but i know this may not be realistic. so it's good to know what is possible.

**Comment by rohrlach** [comment]
So I'm simply saying "Must be image" or "Must be audio" I'm not going to dictate specific formats

**Comment by helenvarley** [comment]
ok; just to note - so far i have successfully uploaded a .png avatar, & had a fail on .swf. for sounds, i have successfully uploaded both .mp3 & .wav. that's all i've tried for now.

**Comment by rohrlach** [comment]
Cool as, again - swf is dead

**Comment by helenvarley** [comment]
is there another format that can play animations? or at least at a minimum, we will need to be able to upload a series of pngs to have frame animation. but it would be good to have another format that can do sophisticated animations.

**Comment by rohrlach** [comment]
There are many - Which one makes sense for us will depend.  Could you raise an issue for 'Animated Avatars'?

**Comment by helenvarley** [comment]
will do. actually, we probably want to be as unrestricted as possible with formats in general. especially if we are able to pull media in on the fly from other sources e.g. vimeo/youtube/flickr etc ...

**Comment by rohrlach** [comment]
Currently, in each case it's just checking mime types for either 'audio' or 'image' it's not looking at specification

**Comment by vickis** [comment]
i just successfully added a gif that appears to animate - in the workshop but have not been able to assign to stage to check :)On 8/05/2017, at 7:19 AM, Paul Rohrlach <notifications@github.com> wrote:Currently, in each case it's just checking mime types for either 'audio' or 'image' it's not looking at specification—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/upstage-org/limelight","title":"upstage-org/limelight","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png" class="">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png" class="">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/upstage-org/limelight" class="">https://github.com/upstage-org/limelight</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rohrlach in #95: Currently, in each case it's just checking mime types for either 'audio' or 'image' it's not looking at specification"}],"action":{"name":"View Issue","url":"<a href="https://github.com/upstage-org/limelight/issues/95#issuecomment-299728138" class="">https://github.com/upstage-org/limelight/issues/95#issuecomment-299728138</a>"}}}
